# DataFrame 的创建

In [1]:
from time import process_time_ns

import pandas as pd
import numpy as np
from numpy.ma.extras import column_stack

# 通过 Series 创建
a = pd.Series([1,2,3,4])
b = pd.Series([5,6,7,8])
df = pd.DataFrame({"第一列":a,"第二列":b})
print(df["第一列"])
# 通过字典来创建
df2 = pd.DataFrame(
    {
        'name':['jak','tokey','mike','joe','amy'],
        'age':[10,20,30,40,50]
     },index=['0001','0002','0003','0004','0005'],
    columns=['name','age']
)
df2

0    1
1    2
2    3
3    4
Name: 第一列, dtype: int64

       name  age
0001    jak   10
0002  tokey   20
0003   mike   30
0004    joe   40
0005    amy   50

# DataFrame 的属性
![](https://cdn.jsdelivr.net/gh/TokeyTuT/my-image-storage@main/img/20260330142236754.png)
* ** 注意如果直接 df[i] 获取的是某一行的数据，如果我们想要获取某一列的数据，我们可以用df[:,'column_name']**

# DataFrame 的访问

In [2]:
df = df2
# 获取单列数据
print(df.name) # Series
print(df['name']) # Series

print(df[['name']])  # DataFrame类型

0001      jak
0002    tokey
0003     mike
0004      joe
0005      amy
Name: name, dtype: str
0001      jak
0002    tokey
0003     mike
0004      joe
0005      amy
Name: name, dtype: str
       name
0001    jak
0002  tokey
0003   mike
0004    joe
0005    amy

In [3]:
# 获取多列数据
df[['name','age']] # DataFrame

       name  age
0001    jak   10
0002  tokey   20
0003   mike   30
0004    joe   40
0005    amy   50

In [4]:
# 查看部分数据
print(df.head(2))
print(df.tail(2))

       name  age
0001    jak   10
0002  tokey   20
     name  age
0004  joe   40
0005  amy   50

In [5]:
# 使用布尔索引筛选
print(df[df.age < 50])

       name  age
0001    jak   10
0002  tokey   20
0003   mike   30
0004    joe   40

In [6]:
# 随机抽样
print(df.sample())

       name  age
0002  tokey   20

# DataFrame 的方法
![](https://cdn.jsdelivr.net/gh/TokeyTuT/my-image-storage@main/img/20260330144200945.png)
![](https://cdn.jsdelivr.net/gh/TokeyTuT/my-image-storage@main/img/20260330144339919.png)

In [7]:
data = pd.DataFrame(
{
    '姓名':['张三','李四','王五','赵六','钱七'],
    '数学':[85,92,78,88,95],
    '英语':[90,88,85,92,80],
    '物理':[75,80,88,85,90]
})
data['总分'] = data[['数学','英语','物理']].sum(axis="columns")
data['平均分'] = data['总分'] / 3
d2 = data[(data['数学'] > 90) | (data['英语']>85)]
print(d2)
d3 = data.sort_values('总分',ascending=False)
print(d3)

   姓名  数学  英语  物理   总分        平均分
0  张三  85  90  75  250  83.333333
1  李四  92  88  80  260  86.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
   姓名  数学  英语  物理   总分        平均分
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
1  李四  92  88  80  260  86.666667
2  王五  78  85  88  251  83.666667
0  张三  85  90  75  250  83.333333

In [8]:
data = pd.DataFrame(
    {
        '产品名称':['A','B','C','D'],
        '单价':[100,150,200,120],
        '销量':[50,30,20,40]
    }
)
data['总销售额'] = data['单价']*data['销量']
data.nlargest(1,columns=['总销售额'])
data.sort_values('总销售额',ascending=False)

  产品名称   单价  销量  总销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000

In [9]:
data = pd.DataFrame(
    {
        '用户 ID':[101,102,103,104,105],
        '用户名':['Alice','Bob','Charlie','David','Eve'],
        '商品类别':['A','B','C','D','E'],
        '商品单价':[1200,300,800,150,200],
        '购买数量':[1,3,2,5,4]
    }
)
data['总销售额'] = data['商品单价']*data['购买数量']
data.nlargest(1,'总销售额')
print(data['总销售额'].mean())
print(data['购买数量'].sum())

1050.0
15